---
  node_timezone: America/New_York
  apt_get_update_threshold_minutes: 5

  tomcat_admin_username: tomcat
  tomcat_admin_password: s3cret
  tomcat_keystore_storepass: changeit
  tomcat_keystore_keypass: changeit
  tomcat_keystore_keystore: /etc/tomcat7/.keystore
  tomcat_keystore_dname: CN=Ryan Ovrevik, OU=development, O=ovrevik.com, L=Milton, S=Georgia, C=US
  tomcat_privileged_ports: true

  mysql_install: true
  # This is populated with a sensible default and thus not necessary. But, we really, really want mysql 5.5.
  mysql_package: mysql-server-5.5 
  mysql_root_password: s3cret
  mysql_bind_address: 0.0.0.0
---